#--------------------------------------------------------------------------#
#									   #
# File:     Malefile							   #
# Subject:  IOS 2021							   #
# Author:   Vladislav Mikheda						   #
# Login:    xmikhe00							   #
# Project:  "IOS – projekt 2 (synchronizace), Santa Claus problem"	   #
#									   #
#--------------------------------------------------------------------------#

all:
	gcc -std=gnu99 -Wall -Wextra -Werror -pedantic -pthread proj2.c -o proj2

remove:
	rm proj2.out
	rm proj2
