#
#Projekt: Projekt č. 1
#Autor: Vladislav Mikheda
#Login: xmikhe00
#
DOK = Proj1

pdf:
	pdflatex ${DOK}.tex
	pdflatex ${DOK}.tex
	
clean:
	rm -f ${DOK}.{aux,dvi,log,ps,out}
	
cleanpdf:
	rm -f ${DOK}.pdf


